import json
from datetime import datetime
from typing import Dict, Any
from app.core.schemas import ExtractedClaimData

class PolicyRulesEngine:
    def __init__(self, policy_path: str = "data/policy_terms.json"):
        with open(policy_path, 'r') as f:
            self.policy = json.load(f)

    def _get_member(self, member_id: str) -> Dict[str, Any]:
        for member in self.policy.get("members", []):
            if member["member_id"] == member_id:
                return member
        return {}

    def calculate_payout(self, state_dict: Dict[str, Any], extracted: ExtractedClaimData) -> Dict[str, Any]:
        member = self._get_member(state_dict["member_id"])
        if not member:
            return {"decision": "REJECTED", "rejection_reasons": ["MEMBER_NOT_FOUND"]}

        category = state_dict["claim_category"].upper()
        claimed_amt = float(state_dict["claimed_amount"])
        treatment_date = datetime.strptime(state_dict["treatment_date"], "%Y-%m-%d")
        join_date = datetime.strptime(member["join_date"], "%Y-%m-%d")
        days_since_joining = (treatment_date - join_date).days

        rejection_reasons = []
        notes_log = []
        global_rejection = False

        if extracted.matched_waiting_period_category:
            required_days = self.policy.get("waiting_periods", {}).get("specific_conditions", {}).get(extracted.matched_waiting_period_category, 0)
            if required_days > 0 and days_since_joining < required_days:
                condition_clean = extracted.matched_waiting_period_category.replace("_", " ")
                rejection_reasons.append("WAITING_PERIOD")
                notes_log.append(f"Treatment for {condition_clean} requires a {required_days}-day waiting period. Member is at {days_since_joining} days.")
                global_rejection = True

        pre_auth_limit = self.policy.get("coverage", {}).get("pre_auth_limit", float('inf'))
        if extracted.requires_pre_auth and claimed_amt > pre_auth_limit:
            uploaded_docs = [d.get("actual_type") for d in state_dict.get("documents", [])]
            if "PRE_AUTHORIZATION_LETTER" not in uploaded_docs:
                rejection_reasons.append("PRE_AUTH_MISSING")
                notes_log.append(f"Pre-authorization is required for high-cost procedures exceeding ₹{pre_auth_limit}, but no Pre-Authorization Letter was uploaded.")
                global_rejection = True
            else:
                notes_log.append("Pre-authorization requirement satisfied by uploaded letter.")

        if extracted.is_diagnosis_excluded:
             rejection_reasons.append("EXCLUDED_CONDITION")
             global_rejection = True

        per_claim_limit = self.policy.get("coverage", {}).get("per_claim_limit", float('inf'))
        if claimed_amt > per_claim_limit:
            rejection_reasons.append("PER_CLAIM_EXCEEDED")
            notes_log.append(f"Claimed amount ₹{claimed_amt} exceeds the universal per-claim limit of ₹{per_claim_limit}.")
            global_rejection = True

        # Line-Item Math Configuration
        cat_config = self.policy.get("opd_categories", {}).get(category.lower(), {})
        approved_total = 0.0
        itemized_breakdown = []
        has_rejected_line_items = False

        hospital_name = extracted.hospital_name or ""
        is_network = any(net_hosp.lower() in hospital_name.lower() for net_hosp in self.policy.get("network_hospitals", []))
        discount_pct = cat_config.get("network_discount_percent", 0) if is_network else 0
        copay_pct = cat_config.get("copay_percent", 0)

        for item in extracted.line_items:
            # FIX: Intercept category layout mismatch tags generated by context-aware prompt rules
            if item.is_policy_excluded or extracted.is_diagnosis_excluded or item.exclusion_reason == "CATEGORY_MISMATCH":
                reason_label = "EXCLUDED_CONDITION"
                if item.exclusion_reason == "CATEGORY_MISMATCH":
                    reason_label = "CATEGORY_MISMATCH"
                    
                itemized_breakdown.append({
                    "item": item.description, 
                    "status": "REJECTED", 
                    "reason": item.exclusion_reason or "EXCLUDED_CONDITION"
                })
                has_rejected_line_items = True
                if reason_label not in rejection_reasons:
                    rejection_reasons.append(reason_label)
                continue

            current_amt = item.amount
            if discount_pct > 0: current_amt -= (current_amt * (discount_pct / 100))
            if copay_pct > 0: current_amt -= (current_amt * (copay_pct / 100))

            approved_total += current_amt
            itemized_breakdown.append({"item": item.description, "status": "APPROVED", "approved_amt": current_amt})

        if discount_pct > 0 and approved_total > 0: notes_log.append(f"Network discount ({discount_pct}%) applied first.")
        if copay_pct > 0 and approved_total > 0: notes_log.append(f"Co-pay ({copay_pct}%) applied.")

        # Capping Limits 
        category_sub_limit = cat_config.get("sub_limit", float('inf'))
        policy_cap = min(per_claim_limit, category_sub_limit)
        hit_limit_cap = False
        
        if approved_total > policy_cap and not global_rejection:
            notes_log.append(f"Payout gracefully capped at ₹{policy_cap} due to policy limits.")
            approved_total = policy_cap
            hit_limit_cap = True

        # Final Adjudication State Synthesis
        if global_rejection or approved_total == 0:
            final_decision = "REJECTED"
            approved_total = 0.0 
        elif has_rejected_line_items or hit_limit_cap:
            final_decision = "PARTIAL"
        else:
            final_decision = "APPROVED"

        return {
            "decision": final_decision,
            "approved_amount": approved_total,
            "rejection_reasons": list(set(rejection_reasons)),
            "itemized_breakdown": itemized_breakdown,
            "notes": " ".join(notes_log).strip()
        }